tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.2/types.yaml
  - /plugin.yaml

inputs:

  bp_dep_archive:
    default: https://github.com/EarthmanT/the-not-blueprint/archive/master.zip
  bp_dep_archive2:
    default: https://github.com/quick-sort/the-not-blueprint/archive/master.zip

node_templates:

  deployment_proxy:
    type: cloudify.nodes.DeploymentProxy
    properties:
      resource_config:
        blueprint:
          id: deployment_proxy
          blueprint_archive: { get_input: bp_dep_archive }
          main_file_name: blueprint.yaml
        deployment:
          id: deployment_proxy
          outputs:
            key: deployment_proxy_output
  deployment_proxy2:
    type: cloudify.nodes.DeploymentProxy
    properties:
      resource_config:
        blueprint:
          id: deployment_proxy_2
          blueprint_archive: { get_input: bp_dep_archive2 }
          main_file_name: blueprint.yaml
        deployment:
          id: deployment_proxy_2
          outputs:
            key: deployment_proxy_output_2
          inputs:
            input_key: { get_attribute: [deployment_proxy, deployment, outputs, deployment_proxy_output]}
    relationships:
      - type: cloudify.relationships.depends_on
        target: deployment_proxy
