Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.2"
  config.vm.box_version = "2.3.1"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.network "forwarded_port", guest: 81, host: 2280

  config.vm.provision "shell", inline: <<-SHELL
    sudo rpm --install /vagrant/cloudify-manager-install-community-*.rpm --verbose
    sudo yum install python-backports-ssl_match_hostname python-setuptools python-backports --assumeyes --verbose
    sudo yum install openssl --assumeyes --verbose
    cfy_manager install --private-ip 127.0.0.1 --public-ip 127.0.0.1 --admin-password "admin" --verbose
  SHELL
end
